name: Deploy Department App

on:
  push:
    branches:
      - main   # or your deploy branch
    paths:
      - 'departments/**'   # only run when student app changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./departments

      - name: Build project
        run: npm run build
        working-directory: ./departments
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_CALLBACK_URL: ${{ vars.VITE_CALLBACK_URL }}
          VITE_API_TIMEOUT: ${{ vars.VITE_API_TIMEOUT }}
          VITE_NODE_ENV: ${{ vars.VITE_NODE_ENV }}

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./departments/dist/
          server-dir: /departments/   # adjust if needed
